2024-07-04 23:08:48,526  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2024-07-04 23:09:05,217 Exception on /checkout [POST]
Traceback (most recent call last):
  File "/home/jose/.local/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jose/.local/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jose/.local/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jose/.local/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/jose/aviancaPlus/availability_service/app.py", line 17, in checkoutBooking
    response = requests.get(
  File "/home/jose/.local/lib/python3.10/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/jose/.local/lib/python3.10/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/jose/.local/lib/python3.10/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/jose/.local/lib/python3.10/site-packages/requests/sessions.py", line 649, in send
    adapter = self.get_adapter(url=request.url)
  File "/home/jose/.local/lib/python3.10/site-packages/requests/sessions.py", line 742, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for 'booking-service:5000/bookings'
2024-07-04 23:09:05,219 127.0.0.1 - - [04/Jul/2024 23:09:05] "[35m[1mPOST /checkout HTTP/1.1[0m" 500 -
2024-07-04 23:10:10,147 Exception on /checkout [POST]
Traceback (most recent call last):
  File "/home/jose/.local/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jose/.local/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jose/.local/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jose/.local/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/jose/aviancaPlus/availability_service/app.py", line 17, in checkoutBooking
    logging.info("success")
  File "/home/jose/.local/lib/python3.10/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/jose/.local/lib/python3.10/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/jose/.local/lib/python3.10/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/jose/.local/lib/python3.10/site-packages/requests/sessions.py", line 649, in send
    adapter = self.get_adapter(url=request.url)
  File "/home/jose/.local/lib/python3.10/site-packages/requests/sessions.py", line 742, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for 'booking-service:5000/bookings'
2024-07-04 23:10:10,149 127.0.0.1 - - [04/Jul/2024 23:10:10] "[35m[1mPOST /checkout HTTP/1.1[0m" 500 -
2024-07-04 23:10:10,891 Exception on /checkout [POST]
Traceback (most recent call last):
  File "/home/jose/.local/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jose/.local/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jose/.local/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jose/.local/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/jose/aviancaPlus/availability_service/app.py", line 17, in checkoutBooking
    logging.info("success")
  File "/home/jose/.local/lib/python3.10/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/jose/.local/lib/python3.10/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/jose/.local/lib/python3.10/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/jose/.local/lib/python3.10/site-packages/requests/sessions.py", line 649, in send
    adapter = self.get_adapter(url=request.url)
  File "/home/jose/.local/lib/python3.10/site-packages/requests/sessions.py", line 742, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for 'booking-service:5000/bookings'
2024-07-04 23:10:10,891 127.0.0.1 - - [04/Jul/2024 23:10:10] "[35m[1mPOST /checkout HTTP/1.1[0m" 500 -
2024-07-04 23:10:31,014  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2024-07-04 23:10:37,004 success
2024-07-04 23:10:37,008 Exception on /checkout [POST]
Traceback (most recent call last):
  File "/home/jose/.local/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jose/.local/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jose/.local/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jose/.local/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/jose/aviancaPlus/availability_service/app.py", line 18, in checkoutBooking
    response = requests.get(
  File "/home/jose/.local/lib/python3.10/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/jose/.local/lib/python3.10/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/jose/.local/lib/python3.10/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/jose/.local/lib/python3.10/site-packages/requests/sessions.py", line 649, in send
    adapter = self.get_adapter(url=request.url)
  File "/home/jose/.local/lib/python3.10/site-packages/requests/sessions.py", line 742, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for 'booking-service:5000/bookings'
2024-07-04 23:10:37,010 127.0.0.1 - - [04/Jul/2024 23:10:37] "[35m[1mPOST /checkout HTTP/1.1[0m" 500 -
